@echo off
title Shahin GRC - Setup Backend Environment
color 0A
echo.
echo ========================================
echo   Setup Backend .env File
echo ========================================
echo.

cd backend

:: Check if .env exists
if exist .env (
    echo ⚠️  Backend .env file already exists!
    echo.
    set /p OVERWRITE="Do you want to update it? (y/n): "
    if /i not "%OVERWRITE%"=="y" (
        echo.
        echo Cancelled. Existing .env file preserved.
        pause
        exit /b
    )
    echo.
    echo Backing up existing .env to .env.backup...
    copy .env .env.backup >nul
)

echo.
echo ========================================
echo   Configure API Keys
echo ========================================
echo.
echo Enter your API keys (press Enter to skip):
echo.

:: OpenAI
set /p OPENAI_KEY="OpenAI API Key (sk-...): "
if "%OPENAI_KEY%"=="" (
    set OPENAI_KEY=sk-your-openai-api-key-here
    echo Using placeholder for OpenAI API Key
) else (
    echo ✅ OpenAI API Key configured
)

:: Google Gemini
set /p GEMINI_KEY="Google Gemini API Key: "
if "%GEMINI_KEY%"=="" (
    set GEMINI_KEY=
    echo Skipping Google Gemini API Key
) else (
    echo ✅ Google Gemini API Key configured
)

:: Azure OpenAI
set /p AZURE_ENDPOINT="Azure OpenAI Endpoint: "
if "%AZURE_ENDPOINT%"=="" (
    set AZURE_ENDPOINT=
    echo Skipping Azure OpenAI Endpoint
) else (
    echo ✅ Azure OpenAI Endpoint configured
)

set /p AZURE_KEY="Azure OpenAI Key: "
if "%AZURE_KEY%"=="" (
    set AZURE_KEY=
) else (
    echo ✅ Azure OpenAI Key configured
)

:: Anthropic
set /p ANTHROPIC_KEY="Anthropic API Key: "
if "%ANTHROPIC_KEY%"=="" (
    set ANTHROPIC_KEY=
    echo Skipping Anthropic API Key
) else (
    echo ✅ Anthropic API Key configured
)

:: AWS Bedrock
set /p AWS_ACCESS_KEY="AWS Access Key ID: "
if "%AWS_ACCESS_KEY%"=="" (
    set AWS_ACCESS_KEY=
    echo Skipping AWS Bedrock
) else (
    echo ✅ AWS Access Key configured
)

set /p AWS_SECRET_KEY="AWS Secret Access Key: "
if "%AWS_SECRET_KEY%"=="" (
    set AWS_SECRET_KEY=
) else (
    echo ✅ AWS Secret Key configured
)

:: Local LLM
set /p LOCAL_LLM_ENDPOINT="Local LLM Endpoint (http://localhost:1234/v1): "
if "%LOCAL_LLM_ENDPOINT%"=="" (
    set LOCAL_LLM_ENDPOINT=http://localhost:1234/v1
)

set /p LOCAL_LLM_MODEL="Local LLM Model (llama-3.2-3b-instruct): "
if "%LOCAL_LLM_MODEL%"=="" (
    set LOCAL_LLM_MODEL=llama-3.2-3b-instruct
)

echo.
echo ========================================
echo   Creating .env File
echo ========================================
echo.

(
    echo # Backend Environment Variables
    echo # Generated by SETUP_BACKEND_ENV.bat
    echo # DO NOT COMMIT THIS FILE TO GIT
    echo.
    echo # Server Configuration
    echo PORT=3001
    echo NODE_ENV=development
    echo FRONTEND_URL=http://localhost:3002
    echo.
    echo # Database
    echo DATABASE_URL=postgresql://user:password@localhost:5432/shahin_grc
    echo.
    echo # JWT Secret
    echo JWT_SECRET=your-jwt-secret-key-here-change-in-production
    echo.
    echo # Admin Secret
    echo ADMIN_SECRET=your-admin-secret-here-change-in-production
    echo.
    echo # Local LLM Configuration
    echo LOCAL_LLM_ENDPOINT=%LOCAL_LLM_ENDPOINT%
    echo LOCAL_LLM_MODEL=%LOCAL_LLM_MODEL%
    echo LOCAL_LLM_TYPE=ollama
    echo.
    echo # OpenAI Configuration
    echo OPENAI_API_KEY=%OPENAI_KEY%
    echo OPENAI_MODEL=gpt-4
    echo.
    echo # Google Gemini Configuration
    if not "%GEMINI_KEY%"=="" (
        echo GOOGLE_GEMINI_API_KEY=%GEMINI_KEY%
        echo GOOGLE_GEMINI_MODEL=gemini-pro
    )
    echo.
    echo # Azure OpenAI Configuration
    if not "%AZURE_ENDPOINT%"=="" (
        echo AZURE_OPENAI_ENDPOINT=%AZURE_ENDPOINT%
        echo AZURE_OPENAI_KEY=%AZURE_KEY%
        echo AZURE_OPENAI_DEPLOYMENT=gpt-4
        echo AZURE_OPENAI_MODEL=gpt-4
        echo AZURE_OPENAI_API_VERSION=2024-02-15-preview
    )
    echo.
    echo # Anthropic Claude Configuration
    if not "%ANTHROPIC_KEY%"=="" (
        echo ANTHROPIC_API_KEY=%ANTHROPIC_KEY%
        echo ANTHROPIC_MODEL=claude-3-sonnet-20240229
    )
    echo.
    echo # AWS Bedrock Configuration
    if not "%AWS_ACCESS_KEY%"=="" (
        echo AWS_ACCESS_KEY_ID=%AWS_ACCESS_KEY%
        echo AWS_SECRET_ACCESS_KEY=%AWS_SECRET_KEY%
        echo AWS_BEDROCK_REGION=us-east-1
        echo AWS_BEDROCK_MODEL=anthropic.claude-3-sonnet-20240229-v1:0
    )
    echo.
    echo # Azure Cognitive Services (Optional)
    echo # AZURE_COMPUTER_VISION_ENDPOINT=https://your-resource.cognitiveservices.azure.com/
    echo # AZURE_SPEECH_ENDPOINT=https://your-resource.cognitiveservices.azure.com/
    echo # AZURE_COGNITIVE_KEY=your-azure-cognitive-key
    echo.
    echo # Hugging Face (Optional)
    echo # HUGGINGFACE_API_KEY=your-huggingface-api-key
    echo.
    echo # RFP Agent API (Optional)
    echo # RFP_AGENT_API_ENDPOINT=http://localhost:8001/api/v1
) > .env

echo ✅ Backend .env file created!
echo.
echo Location: backend\.env
echo.
echo ⚠️  IMPORTANT:
echo - This file is in .gitignore and will NOT be committed to Git
echo - Keep your API keys secure
echo - Never share this file or commit it to version control
echo.
echo ✅ Next steps:
echo 1. Review backend\.env and update any values if needed
echo 2. Start the backend server: npm run dev
echo 3. Test the API: http://localhost:3001/api/ai/health
echo.
pause

